object NameSharedMemoryForm: TNameSharedMemoryForm
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Name'
  ClientHeight = 22
  ClientWidth = 73
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDefault
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
end
